export const services = {
  "bathroom-renovations": {
    label: "Bathroom Renovations",
    businessName: "Inhaus Living",
    heroImage:
      "https://ik.imagekit.io/ijsd2xvnc/Inhaus/carlos-masias-yg8zkwBS30Q-unsplash%20(1).jpg",
    suburbs: [
      // SYDNEY
      "rushcutters-bay",
      "arncliffe",
      "matraville",
      "botany",
      "hillsdale",
      "eastgardens",
      "rosebery",
      "surry-hills",
      "banksmeadow",
      "waverley",
      "clovelly",
      "chippendale",
      "daceyville",
      "paddington",
      "camperdown",
      "maroubra",
      "edgecliff",
      "newtown",
      "double-bay",
      "sydney-cbd",
      "bondi",
      "mascot",
      "haymarket",
      "woollahra",
      "bronte",
      "darlinghurst",
      "darlington",
      "bellevue-hill",
      "pagewood",
      "st-peters",
      "malabar",
      "eastlakes",
      "beaconsfield",
      "kensington",
      "zetland",
      "alexandria",
      "eveleigh",
      "kingsford",
      "erskineville",
      "randwick",
      "waterloo",
      "coogee",
      "port-botany",
      "centennial-park",
      "bondi-beach",
      "tempe",
      "green-square",
      "south-coogee",
      "redfern",
      "queens-park",
      "bondi-junction",
      "moore-park",

      // CANBERRA (apenas 1 página)
      "canberra-act",
    ],
  }
}